// Generated by CoffeeScript 1.6.2
"use strict";
var AWS, AWSTask, fs, glob, path, requiredir, services, _;

glob = require("glob-manifest");

fs = require("fs");

path = require("path");

_ = require("lodash");

requiredir = require("require-dir");

AWS = require("aws-sdk");

services = requiredir("./services");

AWSTask = (function() {
  AWSTask.prototype.defaults = {
    baz: 5
  };

  function AWSTask(grunt, task) {
    this.grunt = grunt;
    this.task = task;
    this.name = this.task.target;
    this.grunt.config.requires(['aws', this.name, 'service']);
    this.data = this.task.data;
    this.service = this.task.data.service;
    this.opts = this.task.options();
    this.done = this.task.async();
    this.config();
  }

  AWSTask.prototype.config = function() {
    var credentials = new AWS.Credentials();
    var that = this;
    credentials.get(function(err) {
      if (err) {
        console.log("error =" + err);
        that.grunt.config.requires(['aws', 'options', 'config', 'accessKeyId']);
        that.grunt.config.requires(['aws', 'options', 'config', 'secretAccessKey']);
        AWS.config.update(that.opts.config);
        return that.startService();
      } else {
        console.log("success");
        console.log(credentials);
        console.log("accessKeyId =" + credentials.accessKeyId );
        console.log("secretAccessKey =" + credentials.secretAccessKey );
        AWS.config.update({
          accessKeyId: credentials.accessKeyId,
          secretAccessKey: credentials.secretAccessKey,
          region: "us-east-1"
        });
        return that.startService();
      } 
    });
  };

  AWSTask.prototype.startService = function() {
    var Service, serviceOpts;

    Service = services[this.service];
    if (!Service) {
      this.grunt.fail.fatal("Sorry the '" + this.service + "' service does not exist yet. Please contribute!");
    }
    if (this.opts[this.service]) {
      serviceOpts = this.opts[this.service];
      console.log (serviceOpts);
      delete this.opts[this.service];
    }
    this.opts = _.extend({}, this.defaults, Service.prototype.defaults || {}, serviceOpts || {}, this.opts);
    this.grunt.log.writeln("Running service: " + this.service + "...");
    new Service(this.grunt, this.opts, this.data, this.done);
    return null;
  };

  return AWSTask;

})();

module.exports = function(grunt) {
  return grunt.registerMultiTask("aws", "A Grunt interface into the Amazon Node.JS SDK", function() {
    return new AWSTask(grunt, this);
  });
};
